### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by valenting** [rosedu/webdev.rosedu.org#3]
A license needs to be chosen for this repo.
All contributors need to agree with the chosen license.
A list of contributors is enclosed below:
- [ ] Dan Serban @dserban
- [ ] Mihai Maruseac @mihaimaruseac
- [ ] Maria Niță @maria
- [ ] @gvoicu

(This message was generated automatically.)

**Comment by ghost** [comment]
The files:
images/logos/webdev_logo.png
js/main.js
are Creative-Commons-licensed (CC-BY-NC with clarifications).

**Comment by maria** [comment]
No need, we will create a new website without any old content.
